import "../styles/globals.css";
import type { AppProps } from "next/app";
import * as robotevents from "robotevents";

robotevents.authentication.setBearer(
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiYzk1MjJiMDlmZWExZmRiYzY1NDBhNzY3MjQwZGYxNGU0NTBhMDM4ODgyYzY4Yjg0OWUwNDg5MTlkZWJmOTg4ZmRkMzQwZjY2NDJmYjZiMjIiLCJpYXQiOjE2NjA2MTYzNTkuNTY5ODc2LCJuYmYiOjE2NjA2MTYzNTkuNTY5ODc5MSwiZXhwIjoyNjA3MzkxMTU5LjU1NTU5NTksInN1YiI6Ijg5ODQ2Iiwic2NvcGVzIjpbXX0.FGmmuHjcmNmxs8wl_ElpX1FB9lwSgD3oVFSCN15tKSLeFwJHSCzprMBXfsm2XDx74DEVz-je1i-os-mej4kwf3FJIVr6OGaNcqHVtyLkLd33ocwCbUHz55rAZKiyB0PM-bv-Iz6lKsOIiClZfVz6MezwlujRuYKa74chDseMCG3fTcLTAZp6zll8aFxtLlLoYA6ESEbLNSxG5Mk_YeAeKRVyR2sNT29xBtMy1ixENTEkINc2bs9K0V6AQAbfjkSdLaSOOVhWGiMXLeeCPOF4DpPQNvt2KOHqnGi_ROImVPyXw2wblwEppcWZ1ZyqJp1y9HLb9o_BjLz_XPk-p8SI3i-NKVvK_TBQlOEF8rCjZbqCBDiJ2-ZOVvTyoQHnrLPnhJ8wtTjTx4xnibNP_w0CJxFeqxxubSoBVx_WeIBD_cJFwfVgVbGrNKSrB9CbFLDytymsNPi0cu-6T3MUx-_6OP69dJWTgibuw9sU-mYl9qBZN1s55XubwEHYP-CtXkJdR-QjOE5xJGLen0LddCnGS5s4TyBZ6uIIulUSfVd3pgywClwVa733BOr9CC3SwcZY7C_o6SSdJIxjoH1L3J7mZTOV-H8NPvt1kwuvxZMnLO-s7CX_Rl7M3YCTuKEqXUVxZ4TXAtVxHi8BgYAE21BrM3R3YA77e9_api3bHnfrnO4"
);

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}

export default MyApp;
