import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import * as robotevents from "robotevents";

function getEvents() {
  return robotevents.events.search({
    level: ["Signature"],
    season: [robotevents.seasons.current("VRC")!],
  });
}

async function getSeason() {
  const number = robotevents.seasons.current("VRC");
  return robotevents.seasons.fetch(number!);
}

const Home: NextPage = () => {
  const [events, setEvents] = useState<robotevents.events.Event[]>([]);
  const [season, setSeason] = useState<robotevents.seasons.Season | null>(null);

  useEffect(() => {
    getEvents().then(setEvents);
    getSeason().then(setSeason);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Season</h1>
        <p>{JSON.stringify(season, null, 4)}</p>
        <h1>Signature Events</h1>
        <ul>
          {events.map((event) => (
            <li key={event.sku}>{event.name}</li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
